server:
  port: 9001
spring:
  application:
    name: retail-spu
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:/tmp/testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    continue-on-error: false
    schema: classpath:db/schema.sql
    initialization-mode: always
  cloud:
    refresh:
      refreshable: none

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-handlers-package: top.zhacker.retail.spu.infra.repo.handler

swagger:
  basePackage: top.zhacker.retail.spu.gate.rest

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/
